AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/bundle
    - db/schema.rb
    - db/migrate/**
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context' ]
