AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/bundle
    - db/schema.rb
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context' ]
